echo 关闭pcm-admin系统开始...
kill -9 `cat /opt/app/pcm/pcm-admin/main.pid`
echo 关闭pcm-admin系统成功...
echo 拷贝编译jar包到应用目录 ...
rm -f /opt/app/pcm/pcm-admin/*.jar
rm -f /opt/app/pcm/pcm-admin/lib/*.jar
cp -f /root/.jenkins/jobs/pcm-admin/workspace/target/pcm-admin-0.0.3-SNAPSHOT.jar /opt/app/pcm/pcm-admin/
cp -f /root/.jenkins/jobs/pcm-admin/workspace/target/lib/*.jar /opt/app/pcm/pcm-admin/lib/
echo 拷贝完成....
echo 开始运行服务...
#后台启动pcm-admin进程
BUILD_ID= java -jar /opt/app/pcm/pcm-admin/pcm-admin-0.0.3-SNAPSHOT.jar  start 8083 8073 >/opt/app/pcm/pcm-admin/pcm-admin.log 2>&1 &
echo $! > /opt/app/pcm/pcm-admin/main.pid
echo 启动完毕.....
